language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule==2.14 apache-libcloud Jinja2==2.10 PyYAML==3.12
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: mTMFrWMSc0V96GqZ6AnYqBnGOtoTL4CLbxKMir2GkK2o8ds42TyMsyCdIxKD/Rim6b2qOLyVuxiMCRT6zdpsLC2vGfDHDb2EGySV1I0qeRSUg5caLNPPf+DxQ6dvhG/jcdoeE4n3L0oPq/A2nUCDc1N1pHKxjGhHiYSlhF4VyVsJcLN5pQc+d+zwmg/pjiZwn4yrkltU5JF85oRAavCx1ED4sLZ4pEdXG23Sp0GwHQlsP4EU503m/0IqXzdDuH00r5U2ZXXtcBWc37JWX9/6bY39uRz95razoOLaQC+GHSYdIWgVGfE60ZLrkQvNG4kMsq39me2WBvbwbr8Zcq6iX1/0kYv6Mc8e0uSHg2oFeykrhUn83vifCPx650FMQjjlaaJ93WOOk01wrVvqYvRDfGVFKdVmpUC4gACPE2FwB4DUm8JgG4UPiGs8lwG/8Lv8LZR08m1zCwnRPJ6jtfF9p2USf5MpnQMlJQSin/GE7cTIZXuQoOd7HOAWxmMUPzpZONotNgUYEPlE9uSINlAXESfqk0xwWYPwR50SagxlLwTTiQDWSoOdusV+7ka824hf89ZWaMgExzL9IdvckRl3wDP66FfgANNI/1UiMlqXaJ1jPuEi0jziYx1mCqmrHvO3H4ANgyHxgBLYkO4NdXIQJCVeuPNN7EAO+dndV2fsQGM=
  - secure: LNUQjAVp3T6/PRpDyGF3ryu37/J12X43DDO9TK3z0OFSEtxwxpwPHwVfIhPW4lx0zA47Dm1R2vrOfAXJfmdSMlCscNHLMvn/AcoIyCuI5Sf/49RafjgeCUy3xkpYe3Hb3xdR9jAdkReb/1afYF0PoGybNpzmnGCzlGR2wzcDXgpikj0cLuPCbofNCzlflezdYG9n+xG+PYO4G5f4artAaXMcs2njC6F8EloH52GwFDDP0GgFVhnJDPkis6+5n3rk/UdsH5Z59vbWUPgqdyyDoRZe86zdUVDnVmems8XzlEm5sIOtjUJG3Zl7GijDdOo4yvzpU8csNOgDVnM6iqSC30bgIeTudPW5FLvxkK3HwqDDaLUjo+Mvkd5cTTL0dQhwKtgmIsLdxWXC83ibYNkgj6LeCl4zc0PCbyI9N/eOeD7Q5/2UUtHMveZIW+WwajqchFWkuP3oDocQ0rR6l+k+xhg0WnLZhElvIKahbxYTWLp6rkcPL9Mi5wzpdKnmAMgfAuCZsRBdrbMiFMNJlQ4lky5jIAXstxoEapPceBS793fPFNA7LnmSBHbYrZ0tRJwOcfxuUgA3km0Km8YBfD3Rzjr8/z13iQ7vh4pgql5FB4CX4y66cuocsWE8qLgkAONdR/YxK8140NZWuRhQ2uN+Vq9TcaTstwUCmcLsWg8mYTo=
  - secure: f0hUB00ScP2dTax+aKD0WxLZdT0UaoWDVjw2bC/WE1ULL6oErPlTrcZjx164qXuwsHC9fXBjiyjjZv52z4PTzYZdFsUlleqb37XfPM4jnsnixOQ2BQ4a7fdeIUxJwFPSriaMyxCKRrJgTS9huOTFQsjn15IBWAj5kb4Kl07bjvfRF0TVBLZ7PiX0fbKTIVkdyyeJz7cgjiM3PyKvmCkrQZRbHjyUyo6VDJBSaUMNbJvGtc8jpg25lp2H91P4PxfqsVK2CW0T0lIU1KZUALaiwJhUcYB+SxWo7suAAReAm540mpnz4vM5bPR+w1ZJ3rYS+lvleG5f+CKAgz+b3hRUtCPvkqo4lMSfyWivE2BYL5/J34GYIuQmpoHg/4lgz89+Y4d1US455YKLJN9ZJD8Hqxm0RDSMEs9Jm4o6gvkz57wN6u7CAywKN32vn3O8ls4ombkf+8lWfGUvCdqDcr0IBOywUXWCknWpr0O3lRZfqYxNHw0CGe0GAxvxll541kJrBFDbuaRSlSNaxrsoF2RXy9Omh20DfjgmFQWe+3JNPac7LmUopHbLRAzY72i5pGvinhkD6LO4F2Qf/Cb4S4/Nw+Ae2C9Cv1BMr8SHwsxxvoOEOSYjGgiPknswjtQqbBdt1tuEMYPpflbE5tucGoICHy3KYgxrF87u8PjbbEv0ji4=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack: devops-team-otus:OQW5TMOgNIemU6RvI9YkzKYc
