language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule==2.14 apache-libcloud Jinja2==2.10 PyYAML==3.12
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: flTiXReFUh70Y7sSElrmp6YNomcXUj0taEugXpMbi4xfn5A1LNlF1OWNh+TToqQpTonJa9fUOMf9igXAHURsGl1kuDuvkdPQL0rYmvbP4YOnq5LbrsIUUUJcSQ+zMJVFD++konEIGJAmr+NK6fxmZyneSKbNbivPZ2CzDgJ1ZRM/FPml0JPXg08W4vJAWc88gbqlIURIamP17oi5R89z8vP53QwNFNiPJidYVUUc6MwrBTtrJadsNFtk3LOc0wPefvaWT6c1PvTs8Vtdg8ESH3EMxkIRjApZLEszvb1fZZgYIjZLXjHEiONn8L+B88H94wGehjhMJ03EjACJreD8q0L+X0L1HL8vgSvZ8FaHOUzCJAiGBqPVFmN29RHLkKVJNbJaAVGyOKDpVHtltH+JUTA5KNTbaB1EmKRJi+n22XqVrGbMMaJ7nUHHY3PTWBqVh+uNtWpnoC9WPgpVt5Cmw8CcQp4kYVjM6ZTCeVsnWU2tNVJCFsc4nokTBE49p5HXGX33QL8dS5xP1qsr2rUgPqBoygf6gwgXL4UI7ff9MLJV4nPj64RBiwu65rVZ4tRMH9M9aQban2atUHFNjjTJBjng51HTn6SeIc4FXMSkG4Im0fGVL5XEs+q+MUDvS+9KCfDyHmYbIDvwxmah5EX/FTC48oeErJzgw+m9NlItPDA=
  - secure: IQeyT6n+HDuKh5xR+MDnpuFaEz8FBNtforae/qki0hXNE/mVrRYjoKNKMTh6TMYiwoEQlUP+W8ZSw3Hm6eQImztkZAU6MX6DpggYa+gTUaLFQXevdlXoypPDx1A4UcVVkEa8CywIysAIai7wF0UigAQGdJIXYYGEr7iLntUrv3WLeV6jkZh1LZV2R/4B3ZINNLb8M9uLhjtJ+xESDCXN7nO2Tt1oROhmbtmvSPHTddpfLjXloPZTYl1aGwI1cRgD7BZmc+k9VkBOAoEqVOCbS8FJJyptozrQqWpxmo+NT+iT4eurKzf9Xx+ARbWj79GPjYmFWBte6woaci/deJdxGga0228UepT1DV6oerTOrFYQIeKJdfRaUhrgx9I64aJzwxhribctgQXhu4DEpaSngU8g+QnzWSMgRp+ypLPlvr6Js95XZsQEBx1isCnZy4bBaQoSshabMFTGxiGg6hUfwsXQQNKwXZ9+nDJTvHkPtTfxHdNYXLccFj6U5rwx5OibyJFdznvW3TQOUmphnmDhEaCU8vlmtRDEuqh1aEr90ed1MKdcJdVl0lf3H1Xs4JbV0EIN/i28CXjIV/Fby4Ve8Mnaqrrtfxnf2KIqDH+/DjC/+H9I9UTSdWjkqCtrGEpikd20UlIHI8lhkpJ63YWvAgQH55tez2F8sCGjhe07Y2U=
  - secure: r1+kbetXz3+ixi/ZSVwGFJx2+kA1dBXiUCvliE9I+N3cFI8Hgf5xzWxPbLi3+aphGXFnDmlEnUqbpLrSUYpRsMVLgVJKfCpRb3+yJovCfFy8n/+OK9QUzfSybMT7UEpwbkjlmffRIBXnljfGXhZTpZi8+6aCu5ioD66IRt62S+eDNSMBY4l0W6w6caYB9Y4DGK7pT+tbyJIek+SonLf8lklE/iC2Hd91XwITZ4FEolE1v/nJiwA7teAlGT4g1QTx60N44Osl1RIpGdrP19Re5v6xfByMeLIL8Q97Lt8JHZAL5usIWK2+fk7hg64GfCyAQX/korTPETh8GgyP4cX8PuEpYvETyavvUZ8aNBpbdztoX68x0Z6NR1O/lQWmhe5iowQaIdgvq0V/oO7WgzCJ9nzy67Y914LwrqPpF26pV/aGcCeT1y6be9S5qha2b2JyZeoIm7wznJAIjxH9HhBNlMeDi0fZupPnSnjKL/ItDMMrTZYCBapkOR5NhW644JxYs8KxoqhpNwHjplQ5vKtCbrVVbc1lhIpatna7jzFqauyXi1lUFsJyIipfBJ3177fDNZa6HiDGfWc3+DFg35ub90pLvKLMl8DgOIG5mzUco0BEFQO8Pa6j0YkWBXcuoG+auScdFx6AXnUfhJcKUrrs2IKLCga2VJDKsfp2uIhgbcY=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack: devops-team-otus:OQW5TMOgNIemU6RvI9YkzKYc
