---
dependency:
  name: galaxy
driver:
  name: gce
platforms:
  - name: instance-travis
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20170919
provisioner:
  name: ansible
verifier:
  name: ansible
